In [ ]:
! pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([2, 4, 5])

In [ ]:
a

In [ ]:
np.arange(100)

In [ ]:
np.__version__

In [ ]:
%timeit b = np.arange(10000)

In [ ]:
b

In [ ]:
%timeit np.arange(10000)

In [ ]:
%timeit range(10000)

In [ ]:
print(range(10000))

In [ ]:
print(range(10))

In [ ]:
a = range(0, 10)

In [ ]:
a


In [ ]:
for a in x

In [ ]:
a = np.arange(100).reshape(20, 1)

In [ ]:
np.arange(100).reshape(20, 5)

In [ ]:
np.arange(100).reshape(20, 5)[2:, 2:]

In [ ]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
a
b

In [ ]:

Z = np.arange(50)
Z = Z[::-1]
print(Z)

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

In [ ]:
type(np.arange(10))

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

In [ ]:
3 * 0.1

In [ ]:
np.array([[0,1],[1,0]])

In [1]:
! pip install numpy

In [2]:
import numpy as np

In [4]:
%timeit range(100000)
%timeit np.arange(100000)

367 ns ± 9.39 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
46.5 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
no = np.arange(10)
print(no)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
no = range(10)
for i in no:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [9]:
np.__version__

'1.15.2'

##Numpy Doc: https://docs.scipy.org/doc/

In [19]:
Z = np.random.random(3)
print(Z)
Z = np.random.randint(100, 1000, [3, 3])
print(Z)

[0.15379902 0.01553446 0.01078139]
[[122 563 409]
 [985 663 590]
 [266 850 126]]


In [25]:
a = np.array([1, 2, 3])
b = np.array([1,2,3])
e = np.array([a, b])
print(e.flatten())
print(a+b)
c = [1, 2, 3]
d = [1, 2, 3]
print(c+d)

[1 2 3 1 2 3]
[2 4 6]
[1, 2, 3, 1, 2, 3]


In [46]:
arr = ["2", "3", "4", "5", "3"]
arb = np.array(arr, dtype=int)
print(arb)
c = np.array([['1.75', '1.68', '1.8', '1.81', '1.69'],
       ['66.4', '49.22', '66.3', '88.56', '65.4']], dtype=float)
print(c)

[2 3 4 5 3]
[[ 1.75  1.68  1.8   1.81  1.69]
 [66.4  49.22 66.3  88.56 65.4 ]]


In [48]:
c[0][3]

1.81

In [51]:
c[1,:2]

array([66.4 , 49.22])

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
b = np.zeros((10, 10))
print(b)
print("%d bytes", (b.size * b.itemsize))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
%d bytes 800


In [70]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [72]:
# Z = Z[1:]
print(Z[1:4])

[11 12 13]


In [88]:
Z = np.arange(24).reshape(3, 2, 4)
print(Z)
print(np.arange(10, 100, 10))

print(np.array([1, 2, 3]))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[10 20 30 40 50 60 70 80 90]
[1 2 3]


In [91]:
Z = np.nonzero([1, 2, 0, 0, 4, 0])
print(Z)
Z = np.array([1, 2, 3, 4])
print(Z[Z != 2])


(array([0, 1, 4]),)
[1 3 4]


In [93]:
Z = np.eye(3, dtype=int)
print(Z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [106]:

Z = np.random.random((3,3))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
print(Z.mean())
print(Z[0].min())
print(np.round(Z[1], 3))

[[0.40278112 0.82261535 0.1643774 ]
 [0.16167357 0.99472673 0.58866355]
 [0.45850417 0.992969   0.71156331]]
0.161673568922018 0.9947267299910346
0.5886526888909178
0.16437739702516407
[0.162 0.995 0.589]


In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

In [111]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)
print(3 * 0.1)
0.1

nan
False
False
nan
False
0.30000000000000004


0.1

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

In [ ]:
print(np.unravel_index(100,(6,7,8)))


In [ ]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

In [ ]:
np.unravel_index([0,7], (2,4))

In [ ]:
np.unravel_index([22, 41, 37], (7,6))

In [ ]:
np.unravel_index(6, (3, 4))

In [ ]:
a, b = np.unravel_index([22, 41, 37], (7,6))
print(a)
print(b)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[W]')
print(Z)

In [ ]:
np.array([2, 4, 5]) * np.array([4, 5, 7])

In [114]:
for dtype in [np.int, np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float16]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-9223372036854775808
9223372036854775807
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
0.000977


In [155]:
a = np.arange(10, 100, 10)
print(a)
index = np.where(np.logical_and(a>=50, a<=100))
print(a[index])
a[np.logical_and(a>=50, a<= 100)]


b = np.array([1, 2, 3, 4, 5, 6])
b[np.array([1, 5])]

[10 20 30 40 50 60 70 80 90]
[50 60 70 80 90]


array([2, 6])

In [156]:
%ls

Numpy.ipynb  data.csv


In [170]:
spending = np.genfromtxt("data.csv", delimiter=",")
print(spending)

[[    nan     nan 211973.     nan]
 [    nan     nan 214277.     nan]
 [    nan     nan 201253.     nan]
 [    nan     nan 203435.     nan]
 [    nan     nan 210154.     nan]
 [    nan     nan 204433.     nan]
 [    nan     nan 207608.     nan]
 [    nan     nan 207256.     nan]
 [    nan     nan 207471.     nan]
 [    nan     nan 209130.     nan]
 [    nan     nan 209198.     nan]
 [    nan     nan 216656.     nan]
 [    nan     nan 213997.     nan]
 [    nan     nan 210873.     nan]
 [    nan     nan 203317.     nan]
 [    nan     nan 206904.     nan]
 [    nan     nan 207997.     nan]
 [    nan     nan 213185.     nan]
 [    nan     nan 212517.     nan]
 [    nan     nan 214568.     nan]
 [    nan     nan 213928.     nan]
 [    nan     nan 217356.     nan]
 [    nan     nan 209417.     nan]
 [    nan     nan 207664.     nan]
 [    nan     nan 207518.     nan]
 [    nan     nan 205679.     nan]
 [    nan     nan 216272.     nan]
 [    nan     nan 216253.     nan]
 [    nan     nan 21

In [174]:
print(spending[:,2].max())
print(spending[:,2].min())
print(spending[:,2].mean())
print(spending[:,2].std())



317598.0
201253.0
265257.655
31641.052112974612
[203435.]
